[package]
name = "chronos-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
chronos-model = { path = "../model" }
chronos-snarks = { path = "../snarks" }
rayon = "1.5"
