[package]
name = "Larity-network"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
libp2p = "0.50"
serde = { version = "1.0", features = ["derive"] }
Larity-model = { path = "../model" }
async-trait = "0.1"
